apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: quickstart
spec:
  version: 8.11.3
  daemonSet:
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
  config:
    outputs:
      default:
        type: elasticsearch
        hosts:
          - "https://training-deployment.kb.us-east-1.aws.found.io:9243"
        password: Uh3MGr7u1CGzPDggTykqnut2
        username: elastic
...